# Generated by Django 6.0 on 2025-12-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profilePicture",
            new_name="profile_picture",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="type",
            new_name="user_type",
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
