# Generated by Django 6.0 on 2025-12-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="isDelivered",
            field=models.BooleanField(default=False),
        ),
    ]
