# Generated by Django 6.0 on 2025-12-26 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_cartitem_wishlistitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="deliveredAt",
            new_name="delivered_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="isDelivered",
            new_name="is_delivered",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="isPaid",
            new_name="is_paid",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="paidAt",
            new_name="paid_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="paymentMethod",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="shippingPrice",
            new_name="shipping_price",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="taxPrice",
            new_name="tax_price",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="totalPrice",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="countInStock",
            new_name="count_in_stock",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="numReviews",
            new_name="num_reviews",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="postalCode",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="wishlistitem",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="isFeatured",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "product")},
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="shipping_address",
                serialize=False,
                to="store.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("user", "product")},
        ),
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
